
opensearch:
  uri: vpc-aicel-opensearch-dev-uaqdecep3vof5ijzumd6l6f6ie.ap-northeast-2.es.amazonaws.com
  username: "os-master-dev"
  password: "!1bigfinance!@QWAS!@"
  region: ap-northeast-2

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  main:
    allow-bean-definition-overriding: true