/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) {
        Dog dog = new Dog();
        Person person = new Person();

        System.out.println("dog is animal? " + isAnimal(dog));
        System.out.println("person is animal? " + isAnimal(person));
    }

    private static boolean isAnimal(Object o) {
        if (!(o instanceof Animal)) {
            return false;
        }
        return true;
    }
}
